[package]
name = "middleware"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
http.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio.workspace = true
tower.workspace = true
tracing = { workspace = true }
